name: CI and CD
on:
  push:
    branches:
      - main
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-verison: "10.x"
      - run: npm install
      - run: npm cache clean --force
      - run: npm run build
        env:
          CI: false
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          CI: false
          GITHUB_TOKEN: ${{ secrets.MY_SECRET }}
